# Generated by Django 4.2.29 on 2026-04-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_owner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='owners/'),
        ),
    ]
