# Generated by Django 4.2.7 on 2026-04-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacy/'),
        ),
    ]
