# Generated by Django 4.2.7 on 2026-04-02 14:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vaccine_name', models.CharField(max_length=200)),
                ('vaccine_brand', models.CharField(blank=True, max_length=200)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('vaccination_date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('skipped', 'Skipped')], default='completed', max_length=20)),
                ('dose_number', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations', to='doctors.doctor')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pets.pet')),
            ],
            options={
                'db_table': 'vaccinations',
                'ordering': ['-vaccination_date'],
            },
        ),
    ]
