# Generated by Django 4.2.29 on 2026-04-02 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('specialization', models.CharField(choices=[('general', 'General Practice'), ('surgery', 'Surgery'), ('dermatology', 'Dermatology'), ('dentistry', 'Dentistry'), ('cardiology', 'Cardiology'), ('orthopedics', 'Orthopedics'), ('ophthalmology', 'Ophthalmology'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('other', 'Other')], default='general', max_length=50)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('qualification', models.CharField(max_length=200)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('available_days', models.JSONField(default=list)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctors',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
