# Generated by Django 4.2.7 on 2026-04-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_attendance_check_out_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_time',
        ),
    ]
