# Generated by Django 4.2.7 on 2026-04-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'ordering': ['id']},
        ),
    ]
