# Generated by Django 4.2.29 on 2026-04-02 11:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('other', 'Other')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('blood_group', models.CharField(choices=[('DEA 1.1+', 'DEA 1.1+'), ('DEA 1.1-', 'DEA 1.1-'), ('DEA 1.2+', 'DEA 1.2+'), ('DEA 1.2-', 'DEA 1.2-'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('microchip_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('allergies', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_neutered', models.BooleanField(default=False)),
                ('is_deceased', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='owners.owner')),
            ],
            options={
                'db_table': 'pets',
                'ordering': ['name'],
            },
        ),
    ]
